[workspace]
members = [
    "rust-book",
    "rust-std",
    "rust-bio",
    "plotters",
    "gtk",
]

[profile.dev]
opt-level=2
lto="off"
# panic = "abort"
incremental=true

[profile.release]
panic = "abort"
opt-level=3
debug=0